Console.Clear();
 
Console.BackgroundColor = ConsoleColor.White;
Console.Write("C");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("O");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("R");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("I");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("N");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("T");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("H");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("I");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("A");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("N");
Console.ResetColor();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("S");
Console.ResetColor();